# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrandiAssign' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrandiAssign
  
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher'
  pod 'Toast-Swift'

  target 'BrandiAssignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrandiAssignUITests' do
    # Pods for testing
  end

end
